name: 'deploy to docker-v.1'
  
on:
  push:
    branches:
      - main

jobs:
  release-docker-image-job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Build image and push to GitHub Packages (Docker Registry)
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
            image: ${{ github.event.repository.name }}
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

  auto-deploy-docker-job:
    needs: release-docker-image-job
    runs-on: self-hosted
    env:
      CONTAINER_NAME: 'akenarin2-vue-app'
      DOCKER_IMAGE_URL: 'ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:${{ github.sha }}'
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: '123.253.62.249'  # production url: 159.223.41.181:9003
        username: 'superuser'
        password: 'Natthaphon@MUC'
        port: '22'
        script: |
          echo ${{ secrets.SUDO_PASSWORD }} | sudo -S docker logout ghcr.io
          echo ${{ secrets.SUDO_PASSWORD }} | sudo -S docker login -u ${{ github.actor }} --password-stdin <<< ${{ secrets.GITHUB_TOKEN }}
          echo ${{ secrets.SUDO_PASSWORD }} | sudo -S docker rm -f ${{ env.CONTAINER_NAME }} || true
          echo ${{ secrets.SUDO_PASSWORD }} | sudo -S docker pull ${{ env.DOCKER_IMAGE_URL }}
          echo ${{ secrets.SUDO_PASSWORD }} | sudo -S docker run --restart=always -d --name ${{ env.CONTAINER_NAME }} -p 9076:80 ${{ env.DOCKER_IMAGE_URL }}
