name: 'deploy to docker'
  
on:
  push:
    branches:
      - main

jobs:
  release-docker-image-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image and push to GitHub Packages (Docker Registry)
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
            image: ${{ github.event.repository.name }}
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

  auto-deploy-docker-job:
    needs: release-docker-image-job
    runs-on: ubuntu-latest
    env:
      CONTAINER_NAME: 'github-app'
      DOCKER_IMAGE_URL: 'ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:${{ github.ref_name }}'
    steps:
    - name: Executing remote SSH commands using password
      uses: JimCronqvist/action-ssh@master
      with:
        host: 'superuser@103.91.190.205'  
        privateKey: ${{ secrets.MY_PRIVATE_KEY}}
        port: '22'
        script: |
          docker logout ghcr.io
          docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}  ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}
          docker rm -f ${{ env.CONTAINER_NAME }} || true
          docker pull ${{ env.DOCKER_IMAGE_URL }}
          docker run --restart=always -d --name ${{ env.CONTAINER_NAME }} -p 9066:80 ${{ env.DOCKER_IMAGE_URL }}

