name: 'deploy to docker-v.1'
  
on:
  push:
    branches:
      - main

jobs:
  release-docker-image-job:
    runs-on: self-hosted 
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/nattha1/github-app:${{ github.sha }} .

      - name: Push Docker image to GitHub Packages
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/nattha1/github-app:${{ github.sha }}

  auto-deploy-docker-job:
    needs: release-docker-image-job
    runs-on: self-hosted
    env:
      CONTAINER_NAME: 'my-web'
      DOCKER_IMAGE_URL: 'ghcr.io/nattha1/github-app:${{ github.sha }}'
    steps:
      - name: Execute SSH commands on remote server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 'superuser@123.253.62.249'
        privateKey: ${{ secrets.MY_PRIVATE_KEY }}
        command: |
          docker logout ghcr.io
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker rm -f my-web || true
          docker pull ghcr.io/nattha1/github-app:latest
          docker run --restart=always -d --name my-web -p 9002:3000 ghcr.io/nattha1/github-app:latest
    
