name: 'deploy to docker-v.1'
  
on:
  push:
    branches:
      - main

jobs:
  release-docker-image-job:
    runs-on: self-hosted  # Ensure that this runner is on your local machine with Docker Desktop
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/nattha1/github-app:${{ github.sha }} .

      - name: Push Docker image to GitHub Packages
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/nattha1/github-app:${{ github.sha }}

  auto-deploy-docker-job:
    needs: release-docker-image-job
    runs-on: self-hosted
    env:
      CONTAINER_NAME: 'my-web'
      DOCKER_IMAGE_URL: 'ghcr.io/nattha1/github-app:${{ github.sha }}'
    steps:
    - name: Execute SSH commands on remote server
      uses: JimCronqvist/action-ssh@master
      with:
        host: 'superuser@123.253.62.249'  # replace with your server's IP or hostname
        privateKey: ${{ secrets.MY_PRIVATE_KEY }}
        command: |
          docker logout ghcr.io
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker rm -f ${{ env.CONTAINER_NAME }} || true
          docker pull ${{ env.DOCKER_IMAGE_URL }}
          docker run --restart=always -d --name ${{ env.CONTAINER_NAME }} -p 9002:3000 ${{ env.DOCKER_IMAGE_URL }}
