name: 'deploy to docker'
  
on:
  push:
    branches:
      - main 

jobs:
  release-docker-image-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image and push to GitHub Packages (Docker Registry)
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
            image: ${{ github.event.repository.name }}
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

  auto-deploy-docker-job:
    needs: release-docker-image-job
    runs-on: ubuntu-latest
    env:
      CONTAINER_NAME: 'natthaphon-vue-app'
      DOCKER_IMAGE_URL: 'ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:${{ github.ref_name }}'
    steps:
    - name: Executing remote SSH commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: '103.91.190.205'  
        username: 'superuser'
        password: 'Natthaphon@MUC'
        port: '22'
        script: |
          sudo docker logout ghcr.io
          echo ${{ secrets.GITHUB_TOKEN }} | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin
          sudo docker rm -f ${{ env.CONTAINER_NAME }} || true
          sudo docker pull ${{ env.DOCKER_IMAGE_URL }}
          sudo docker run --restart=always -d --name ${{ env.CONTAINER_NAME }} -p 9003:80 ${{ env.DOCKER_IMAGE_URL }}
