name: 'deploy to docker'
  
on:
  push:
    branches:
      - main 

jobs:
  release-docker-image-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image and push to GitHub Packages (Docker Registry)
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ github.event.repository.name }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  auto-deploy-docker-job:
    needs: release-docker-image-job
    runs-on: ubuntu-latest
    env:
      CONTAINER_NAME: 'natthaphon-app'
      DOCKER_IMAGE_URL: 'ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:${{ github.ref_name }}'
    steps:
    - name: Setting up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Executing remote SSH commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: '103.91.190.205'  
        username: 'superuser'
        port: '22'
        script: |
          docker logout ghcr.io
          docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker rm -f ${{ env.CONTAINER_NAME }} || true
          docker pull ${{ env.DOCKER_IMAGE_URL }}
          docker run --restart=always -d --name ${{ env.CONTAINER_NAME }} -p 9003:80 ${{ env.DOCKER_IMAGE_URL }}
