ame: 'deploy to docker'
  
on:
  push:
    branches:
      - main

jobs:
  release-docker-image-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image and push to GitHub Packages (Docker Registry)
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
            image: ${{ github.event.repository.name }}
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

  auto-deploy-docker-job:
    needs: release-docker-image-job
    runs-on: ubuntu-latest
    env:
      CONTAINER_NAME: 'my-html-container'
      DOCKER_IMAGE_URL: 'ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:${{ github.ref_name }}'
    steps:
    - name: Executing remote SSH commands using password
      uses: JimCronqvist/action-ssh@master
      with:
        host: 'superuser@103.91.190.205'  
        privateKey: ${{ secrets.MY_PRIVATE_KEY}}
        port: '22'
        script: |
          sudo docker logout ghcr.io
          sudo docker login -u Nattha1 -p *** ghcr.io/Nattha1/github-app
          sudo docker rm -f akenarin2-vue-app || true
          sudo docker pull ghcr.io/nattha1/github-app:main
          sudo docker run --restart=always -d --name akenarin2-vue-app -p 9076:80 ghcr.io/nattha1/github-app:main


