name: 'deploy'
  
on:
    push:
        tags:
            - '*'

jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set node ver 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - run: npm ci

      - name: Run build production (create dist folder)
        run: npm run build